export { default as GitHub } from "./Github.svg"
export { default as LinkedIn } from "./LinkedIn.svg"
export { default as Instagram } from "./Instagram.svg"

export { default as HtmlIcon } from "./Html.svg"
export { default as CssIcon } from "./Css.svg"
export { default as JavaScriptIcon } from "./Javascript.svg"
export { default as TypeScriptIcon } from "./Typescript.svg"
export { default as ReactIcon } from "./React.svg"
export { default as NodeJsIcon} from "./Nodejs.svg"