export { default as GitHub } from "./GitHub.svg"
export { default as LinkedIn } from "./LinkedIn.svg"
export { default as Instagram } from "./Instagram.svg"

export { default as HtmlIcon } from "./Html.svg"
export { default as CssIcon } from "./Css.svg"
export { default as JavaScriptIcon } from "./JavaScript.svg"
export { default as TypeScriptIcon } from "./TypeScript.svg"
export { default as ReactIcon } from "./React.svg"
export { default as NodeJsIcon} from "./NodeJs.svg"